# Blog info
blog_name: Iceberg
slogan: Being the man in whom the tiger sniffs the rose
url: http://www.icebergcwp.com

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: iceberg,Maxos,iOS,nodejs,JavaScript

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: Project
    url: /project/
    target_blank: true #在新页面打开
  - name: Github
    url: https://github.com/icebergcwp1990
    target_blank: true
  - name: Twitter
    url: https://twitter.com/IcebergCao
    target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: true # true|fase
  text: 交换友链可以邮件 icebergcwp1990@gmail.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: Kick my ass
  tip: Buy me a coke ?
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
#personal_style: /css/personal-style.css #关闭自定义样式

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: 57e94d016e201fba3603a8a2b0263af0

# Comment service
# disqus_shortname: iceberg
duoshuo_shortname: iceberg

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "Iceberg，1990."
    - "看书，编程，打篮球，听民谣."
    - "MacOS & iOS 应用开发工程师，常用 Objective-C / JavaScript."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@iceberg"
    text_value_url: https://github.com/icebergcwp1990
  - type: weibo
    icon: icon-weibo
    text_key: 微博
    text_value: "@iceberg"
    text_value_url: http://weibo.com/u/5153417297
  - type: mail
    icon: icon-mail
    text_key: Gmail
    text_value: "icebergcwp1990r@gmail.com"
  - type: location
    icon: icon-location
    text_value: 长沙

link:
  - name: 阮一峰
    info: ruanyf
    url: http://www.ruanyifeng.com/home.html
    avatar: https://avatars1.githubusercontent.com/u/905434?v=3&s=400
  - name: KALZUMEUS
    info: Patrick McKenzie
    url: http://www.kalzumeus.com/
    avatar: https://avatars0.githubusercontent.com/u/6274940?v=3&s=100
  - name: COCOA SAMURAI
    info: I am a Cocoa Developer & Enthusiast working on Mac & iOS apps. 
    url: http://cocoasamurai.blogspot.jp/
    avatar: https://avatars3.githubusercontent.com/u/2963?v=3&s=400

project:
  - type: personal
    name: VASandboxFileAccess
    url: https://github.com/icebergcwp1990/VASandboxFileAccess
    intro: sandboxing aware file access glue code 
