# Blog info
blog_name: Iceberg
slogan: Being the man in whom the tiger sniffs the rose
url: http://icebergcwp.com

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: Horseman, Mac OS/iOS, Python, 健身, 读书, 尤克里里

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  #- name: Project
  #  url: /project/
  #  target_blank: true #在新页面打开
  - name: Github
    url: https://github.com/icebergcwp1990
    target_blank: true
  - name: About
    url: /about/
    target_blank: false

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 导航

search_slogan:
  isShow: true # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: true # true|fase
  text: Send email to industriousonesoft@gmail.com or icebergcwp1990@163.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: Kick my ass
  tip: Buy me a coke ?
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png

post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
#personal_style: /css/personal-style.css #关闭自定义样式

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: 275aa94150d7be3f234542686997bdfa

# Comment service
disqus_shortname: http-icebergcwp-com
# duoshuo_shortname: Horseman
# gitment_shortname: Horseman
# gitalk_shortname: Horseman

busuanzi: true

# 自动生成sitemap
sitemap: 
    path: sitemap.xml
baidusitemap:
    path: baidusitemap.xml


# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "一个正在努力让自己变得有趣的人，目前以从事MacOS/iOS开发谋生，非传统意义上的程序员，喜欢健身和读书，偏好心理、历史、传记和经济方面的书籍。"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@iceberg"
    text_value_url: https://github.com/icebergcwp1990
  - type: weibo
    icon: icon-weibo
    text_key: 微博
    text_value: "@iceberg"
    text_value_url: http://weibo.com/u/5153417297
  - type: mail
    icon: icon-mail
    text_key: Gmail
    text_value: "industriousonesoft@gmail.com"
  - type: location
    icon: icon-location
    text_value: ChangSha

link:
  - name: 阮一峰的个人网站
    info: ruanyf
    url: http://www.ruanyifeng.com/home.html
    avatar: https://avatars1.githubusercontent.com/u/905434?v=3&s=400
  - name: 王垠个人博客
    info: 当然我在扯淡
    url: http://www.yinwang.org
    avatar: http://cdn.v2ex.com/avatar/6f6d/7ea7/5645_large.png?m=1335126528
  - name: 小卷的胡言乱语
    info: 一个有趣且会享受的生活的人
    url: https://salu099.github.io/blog/
    avatar: https://salu099.github.io/blog/img/headimg.png
  - name: Sergio Chan
    info: Full Stack, Born hacker, Professional Manager
    url: http://sergiochan.xyz/archives/
    avatar: https://avatars2.githubusercontent.com/u/10103766?v=3&s=460
  - name: 唐巧的博客
    info: 记录下自己学习的点滴
    url: http://blog.devtang.com
    avatar: http://ww4.sinaimg.cn/small/65dc76a3jw8exkme9y57dj20yi0ymabn.jpg
  - name: KALZUMEUS
    info: Patrick McKenzie
    url: http://www.kalzumeus.com/
    avatar: https://avatars0.githubusercontent.com/u/6274940?v=3&s=100
  - name: COCOA SAMURAI
    info: I am a Cocoa Developer & Enthusiast working on Mac & iOS apps. 
    url: http://cocoasamurai.blogspot.jp/
    avatar: https://avatars3.githubusercontent.com/u/2963?v=3&s=400
  - name: Aditya Bhargava
    info: You've reached Adit's homepage
    url: http://adit.io/
    avatar: https://avatars0.githubusercontent.com/u/97219?s=460&v=4

project:
  - type: public
    name: CustomRunLoopInputSourceDemo
    url: https://github.com/icebergcwp1990/CustomRunLoopInputSourceDemo
    intro: A demo show how to custom input source in run loop
  - type: public
    name: NSStreamOnNon-MainThread
    url: https://github.com/icebergcwp1990/NSStreamOnNon-MainThread
    intro:  NSStream schedule in runloop of non-main thread
